#!/bin/bash
# Copyright 2021 The FydeOS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
# Author: Yang Tsao<yang@fydeos.io>

source $(dirname $0)/lib/importlib.sh
#DEBUG_MODE=true

import_libs format_color array_util console

import_libs root

root_show_help() {
  echo "main help"
}

main() {
  set_appname "FydeOS hardware tuning"
  set_appversion 0 0 1
  register_console root
}

main $@
