#!/bin/bash
# Copyright 2021 The FydeOS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
# Author: Yang Tsao<yang@fydeos.io>
declare RealPath=$0
if [ -h $0 ]; then
  RealPath=$(readlink $RealPath)
fi
source $(dirname $RealPath)/lib/importlib.sh

if [ "$production" == "debug" ]; then
  DEBUG_MODE=true
fi
if [[ "$1" = "--info" ]]; then
  COLOR="false"
fi

import_libs format_color array_util console

import_libs root

root_show_help() {
  echo "main help"
}

main() {
  set_appname "FydeOS Hardware Tuner"
  set_appversion 0 0 1
  if [[ "$1" = "--info" ]]; then
    show_dmi_info
    exit 0
  fi
  register_console root
}

main $@
